### ISSUE TITLE
What's the point of using ... in function arguments if they're not used?

### ISSUE THREAD

**Issue by wdearden2** [r-lib/clock#239]
https://clock.r-lib.org/reference/date-time-parse.html

R will still throw an error if you try to use an unused argument so what's the point of using dot arguments if you're not going to use them? Is it just to force format and locale are used as keyword arguments?

**Comment by wdearden2** [comment]
nvm it makes sense

**Comment by DavisVaughan** [comment]
I think this is a good question, so even though you seem to have figured it out I will answer it anyways in case anyone else wanders by and has the same question.

This is a fairly new pattern we have been trying out in tidyverse / r-lib packages. It is outlined a little bit here in the design guide https://design.tidyverse.org/dots-position.html, in particular in the "Why is it important" section https://design.tidyverse.org/dots-position.html#what-is-it-important. I think that clock is one of the first packages to fully buy into this pattern, but I really like it.

For me, there are two major benefits:

1. It makes user written code more readable and more robust. For the most part, you'll notice that the dots separate required arguments from optional ones (i.e. ones that already have a default). When setting an optional argument, it is often more informative to future you (when you come back and read it in 6 months) to specify that optional argument by name. For example, if somehow we could make the POSIXct method of `date_group()` not use dots, a user could write:

   ```r
   date_group(Sys.time(), "year", 2, "next", "roll-forward", "earliest")
   ```

   While this nicely fits in 1 line, I think that if I were to read this a month from now, then I'd forget what all the options specify. I personally greatly prefer the following. I think spreading it over multiple lines is a benefit here, not a drawback:

   ```r
   date_group(
     Sys.time(), 
     "year", 
     n = 2, 
     invalid = "next", 
     nonexistent = "roll-forward", 
     ambiguous = "earliest"
   )
   ```

2. I mentioned above that it makes user code more robust. This has to do with my second point, which is that it makes my life as a developer a little easier if I want to add a new optional argument. Say I want to add some hypothetical `adjust = NULL` argument to `date_group()`. This might be specific to `date_group()`, so it makes the most sense to add it after `n` but before `invalid`, so:
   
   ```r
   date_group(x, precision, ..., n = 1L, adjust = NULL, invalid = NULL, nonexistent = NULL, ambiguous = x)
   ```

   But now I have to worry about the user in 1. who specified arguments without names, like `(2, "next")`, since now `"next"` positionally lines up with `adjust` rather than `invalid`. Forcing users to specify the optional argument by name allows me to add new optional arguments wherever I'd like, without the risk of breaking user code.
