### ISSUE TITLE
feature request: add support for dbplyr

### ISSUE THREAD

**Issue by brunocarlin** [r-lib/clock#248]
Right now, the only way to do time operations on a database is using lubridate. Have you guys considered how to implement the clock package with dbplyr?

I have been using RAthena.

**Comment by DavisVaughan** [comment]
I think that the lubridate-dbplyr interface will always continue to work, so I would stick with that for the intermediate term.

It is possible that clock will be the backend for lubridate operations in the future. Then it would make sense for lubridate to continue to be the API for dbplyr translation. We are still trying to decide whether or not that is the right path forward. If we don't do that, then we could consider adding dbplyr translations for clock.

I'm going to close this issue, since this is something that I am aware of and have been thinking about, but will have to come back to in the far future
